Question 6 -
Using the data from Question 3, write code to analyze the data and answer the following questions Note 
1. Draw plots to demonstrate the analysis for the following questions for better visualizations.
2. Write code comments wherever required for code understanding
Insights to be drawn -
```● Get all Pokemons whose spawn rate is less than 5%
● Get all Pokemons that have less than 4 weaknesses
● Get all Pokemons that have no multipliers at all
● Get all Pokemons that do not have more than 2 evolutions
● Get all Pokemons whose spawn time is less than 300 seconds.
Note - spawn time format is "05:32”, so assume “minute: second” format and perform the analysis.
● Get all Pokemon who have more than two types of capabilities
```

In [3]:
import pandas as pd

In [4]:
link = 'https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json'

In [7]:
df = pd.read_json(link)
df

                                               pokemon
0    {'id': 1, 'num': '001', 'name': 'Bulbasaur', '...
1    {'id': 2, 'num': '002', 'name': 'Ivysaur', 'im...
2    {'id': 3, 'num': '003', 'name': 'Venusaur', 'i...
3    {'id': 4, 'num': '004', 'name': 'Charmander', ...
4    {'id': 5, 'num': '005', 'name': 'Charmeleon', ...
..                                                 ...
146  {'id': 147, 'num': '147', 'name': 'Dratini', '...
147  {'id': 148, 'num': '148', 'name': 'Dragonair',...
148  {'id': 149, 'num': '149', 'name': 'Dragonite',...
149  {'id': 150, 'num': '150', 'name': 'Mewtwo', 'i...
150  {'id': 151, 'num': '151', 'name': 'Mew', 'img'...

[151 rows x 1 columns]

In [6]:
data = df.pokemon
dn = pd.json_normalize(data)
dn

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.8399999999999999]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN

### ● Get all Pokemons that have less than 4 weaknesses

In [13]:
dn.weaknesses

0      [Fire, Ice, Flying, Psychic]
1      [Fire, Ice, Flying, Psychic]
2      [Fire, Ice, Flying, Psychic]
3             [Water, Ground, Rock]
4             [Water, Ground, Rock]
                   ...
146            [Ice, Dragon, Fairy]
147            [Ice, Dragon, Fairy]
148      [Ice, Rock, Dragon, Fairy]
149              [Bug, Ghost, Dark]
150              [Bug, Ghost, Dark]
Name: weaknesses, Length: 151, dtype: object

In [36]:
lst =[]
for idx,val in enumerate(dn.weaknesses):
    if len(val)<4:
        lst.append(idx)

In [38]:
dn.loc[lst]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
5,6,006,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"[Fire, Flying]",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,None,"[Water, Electric, Rock]",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':..."
6,7,007,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,[Water],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"[Electric, Grass]","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",NaN
7,8,008,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,[Water],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"[Electric, Grass]","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"[Fire, Flying]",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Water, Electric, Rock]",NaN,NaN
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.8399999999999999]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN

These are all the Pokemons that have less than 4 weaknesses.

### ● Get all Pokemons that have no multipliers at all

In [49]:
dn.columns

Index(['id', 'num', 'name', 'img', 'type', 'height', 'weight', 'candy',
       'candy_count', 'egg', 'spawn_chance', 'avg_spawns', 'spawn_time',
       'multipliers', 'weaknesses', 'next_evolution', 'prev_evolution'],
      dtype='object')

In [50]:
dn.multipliers.describe()

count        70
unique       68
top       [1.4]
freq          2
Name: multipliers, dtype: object

In [57]:
dn[dn.multipliers.isnull()]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
5,6,006,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"[Fire, Flying]",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,None,"[Water, Electric, Rock]",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':..."
8,9,009,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,[Water],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,None,"[Electric, Grass]",NaN,"[{'num': '007', 'name': 'Squirtle'}, {'num': '..."
11,12,012,Butterfree,http://www.serebii.net/pokemongo/pokemon/012.png,"[Bug, Flying]",1.09 m,32.0 kg,Caterpie Candy,NaN,Not in Eggs,0.0220,2.20,05:23,None,"[Fire, Electric, Ice, Flying, Rock]",NaN,"[{'num': '010', 'name': 'Caterpie'}, {'num': '..."
14,15,015,Beedrill,http://www.serebii.net/pokemongo/pokemon/015.png,"[Bug, Poison]",0.99 m,29.5 kg,Weedle Candy,NaN,Not in Eggs,0.0510,5.10,04:50,None,"[Fire, Flying, Psychic, Rock]",NaN,"[{'num': '013', 'name': 'Weedle'}, {'num': '01..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,145,145,Zapdos,http://www.serebii.net/pokemongo/pokemon/145.png,"[Electric, Flying]",1.60 m,52.6 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Ice, Rock]",NaN,NaN
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"[Fire, Flying]",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Water, Electric, Rock]",NaN,NaN
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN

These are all Pokemons that have no multipliers at all.

### Get all Pokemons that do not have more than 2 evolutions

In [156]:
dn[['next_evolution','prev_evolution']].describe(include='all')

                             next_evolution                     prev_evolution
count                                    70                                 72
unique                                   70                                 70
top     [{'num': '080', 'name': 'Slowbro'}]  [{'num': '133', 'name': 'Eevee'}]
freq                                      1                                  3

In [157]:
dn[['next_evolution','prev_evolution']].isnull().sum()

next_evolution    81
prev_evolution    79
dtype: int64

There are null values in these columns, we need to fill it with an empty dictionary so that we can calculate the len of that dictionary as zero.

In [158]:
df=dn.copy()

In [159]:
df['next_evolution']=df['next_evolution'].fillna('{}')

In [160]:
df['prev_evolution']=df['prev_evolution'].fillna('{}')

In [161]:
df[['next_evolution','prev_evolution']].head()

,next_evolution,prev_evolution
0,"[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",{}
1,"[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,{},"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,"[{'num': '005', 'name': 'Charmeleon'}, {'num':...",{}
4,"[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [162]:
lst = []
for i in range(df.shape[0]):
    if (len(df.next_evolution[i])+len(df.prev_evolution[i])) <=2:
        lst.append(i)

In [163]:
lst

[1, 4, 7, 10, 13, 16, 29, 32, 43, 60, 63, 66, 69, 74, 92, 147]

In [164]:
df.iloc[lst]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
7,8,008,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,[Water],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.034,3.4,07:02,[1.4],"[Electric, Grass]","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]"
10,11,011,Metapod,http://www.serebii.net/pokemongo/pokemon/011.png,[Bug],0.71 m,9.9 kg,Caterpie Candy,50.0,Not in Eggs,0.187,18.7,02:11,"[3.55, 3.79]","[Fire, Flying, Rock]","[{'num': '012', 'name': 'Butterfree'}]","[{'num': '010', 'name': 'Caterpie'}]"
13,14,014,Kakuna,http://www.serebii.net/pokemongo/pokemon/014.png,"[Bug, Poison]",0.61 m,10.0 kg,Weedle Candy,50.0,Not in Eggs,0.440,44.0,02:30,"[3.01, 3.41]","[Fire, Flying, Psychic, Rock]","[{'num': '015', 'name': 'Beedrill'}]","[{'num': '013', 'name': 'Weedle'}]"
16,17,017,Pidgeotto,http://www.serebii.net/pokemongo/pokemon/017.png,"[Normal, Flying]",1.09 m,30.0 kg,Pidgey Candy,50.0,Not in Eggs,1.020,102.0,01:30,[1.79],"[Electric, Rock]","[{'num': '018', 'name': 'Pidgeot'}]","[{'num': '016', 'name': 'Pidgey'}]"
29,30,030,Nidorina,http://www.serebii.net/pokemongo/pokemon/030.png,[Poison],0.79 m,20.0 kg,Nidoran ♀ (Female) Candy,100.0,Not in Eggs,0.088,8.8,07:22,"[1.83, 2.48]","[Ground, Psychic]","[{'num': '031', 'name': 'Nidoqueen'}]","[{'num': '029', 'name': 'Nidoran(Female)'}]"
32,33,033,Nidorino,http://www.serebii.net/pokemongo/pokemon/033.png,[Poison],0.89 m,19.5 kg,Nidoran ♂ (Male) Candy,100.0,Not in Eggs,0.083,8.3,09:02,[1.83],"[Ground, Psychic]","[{'num': '034', 'name': 'Nidoking'}]","[{'num': '032', 'name': 'Nidoran(Male)'}]"
43,44,044,Gloom,http://www.serebii.net/pokemongo/pokemon/044.png,"[Grass, Poison]",0.79 m,8.6 kg,Oddish Candy,100.0,Not in Eggs,0.064,6.4,11:33,[1.49],"[Fire, Ice, Flying, Psychic]","[{'num': '045', 'name': 'Vileplume'}]","[{'num': '043', 'name': 'Oddish'}]"
60,61,061,Poliwhirl,http://www.serebii.net/pokemongo/pokemon/061.png,[Water],0.99 m,20.0 kg,Poliwag Candy,100.0,Not in Eggs,0.130,13.0,09:14,[1.9500000000000002],"[Electric, Grass]","[{'num': '062', 'name': 'Poliwrath'}]","[{'num': '060', 'name': 'Poliwag'}]"
63,64,064,Kadabra,http://www.serebii.net/pokemongo/pokemon/064.png,[Psychic],1.30 m,56.5 kg,Abra Candy,100.0,Not in Eggs,0.027,2.7,11:25,[1.4],"[Bug, Ghost, Dark]","[{'num': '065', 'name': 'Alakazam'}]","[{'num': '063', 'name': 'Abra'}]"
66,67,067,Machoke,http://www.serebii.net/pokemongo/pokemon/067.png,[Fighting],1.50 m,70.5 kg,Machop Candy,100.0,Not in Eggs,0.034,3.4,10:32,[1.7000000000000002],"[Flying, Psychic, Fairy]","[{'num': '068', 'name': 'Machamp'}]","[{'num': '066', 'name': 'Machop'}]"
69,70,070,Weepinbell,http://www.serebii.net/pokemongo/pokemon/070.png,"[Grass, Poison]",0.99 m,6.4 kg,Bellsprout Candy,100.0,Not in Eggs,0.072,7.2,09:45,[1.5899999999999999],"[Fire, Ice, Flying, Psychic]","[{'num': '071', 'name': 'Victreebel'}]","[{'num': '069', 'name': 'Bellsprout'}]"
74,75,075,Graveler,http://www.serebii.net/pokemongo/pokemon/075.png,"[Rock, Ground]",0.99 m,105.0 kg,Geodude Candy,100.0,Not in Eggs,0.071,7.1,04:53,"[1.6400000000000001, 1.72]","[Water, Grass, Ice, Fighting, Ground, Steel]","[{'num': '076', 'name': 'Golem'}]","[{'num': '074', 'name': 'Geodude'}]"
92,93,093,Haunter,http://www.serebii.net/pokemongo/pokemon/093.png,"[Ghost, Poison]",1.60 m,0.1 kg,Gastly Candy,100.0,Not in Eggs,0.052,5.2,00:10,"[1.56, 1.8]","[Ground, Psychic, Ghost, Dark]","[{'num': '094', 'name': 'Gengar'}]","[{'num': '092', 'name': 'Gastly'}]"
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.020,2.0,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"

These are all Pokemons that do not have more than 2 evolutions.

### ● Get all Pokemons whose spawn time is less than 300 seconds.
Note - spawn time format is "05:32”, so assume “minute: second” format and perform the analysis.

In [195]:
dn = df.copy()

In [196]:
dn[['spawn_time']].head()

  spawn_time
0      20:00
1      07:00
2      11:30
3      08:45
4      19:00

In [198]:
dn[['spawn_time']].describe()

       spawn_time
count         151
unique        126
top           N/A
freq            6

In [199]:
# replacing N/A values by 0:0
dn.spawn_time = dn.spawn_time.replace('N/A','0:0')

In [200]:
dn.spawn_time.isnull().sum()

0

In [201]:
# add two new columns for time in minutes and seconds
dn['sp_min']=0
dn['sp_sec']=0
for i in range(dn.shape[0]):
    a,b = dn.spawn_time[i].split(":")
    dn['sp_min'][i]=a
    dn['sp_sec'][i]=b

C:\Users\Shailendra\AppData\Local\Temp\ipykernel_6112\310437552.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dn['sp_min'][i]=a
C:\Users\Shailendra\AppData\Local\Temp\ipykernel_6112\310437552.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dn['sp_sec'][i]=b

In [202]:
dn

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,sp_min,sp_sec
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",{},20,0
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",7,0
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",{},"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",11,30
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",{},8,45
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.8399999999999999]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",{},6,41
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",11,57
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",{},"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",23,38
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0:0,None,"[Bug, Ghost, Dark]",{},{},0,0
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0:0,None,"[Bug, Ghost, Dark]",{},{},0,0

In [203]:
# make a new column having time in total seconds
dn['sp_time'] = dn['sp_min']*60+dn['sp_sec']

In [205]:
dn[dn.sp_time<300]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,sp_min,sp_sec,sp_time
6,7,007,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,[Water],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"[Electric, Grass]","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",{},4,25,265
8,9,009,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,[Water],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,None,"[Electric, Grass]",{},"[{'num': '007', 'name': 'Squirtle'}, {'num': '...",0,6,6
10,11,011,Metapod,http://www.serebii.net/pokemongo/pokemon/011.png,[Bug],0.71 m,9.9 kg,Caterpie Candy,50.0,Not in Eggs,0.1870,18.70,02:11,"[3.55, 3.79]","[Fire, Flying, Rock]","[{'num': '012', 'name': 'Butterfree'}]","[{'num': '010', 'name': 'Caterpie'}]",2,11,131
12,13,013,Weedle,http://www.serebii.net/pokemongo/pokemon/013.png,"[Bug, Poison]",0.30 m,3.2 kg,Weedle Candy,12.0,2 km,7.1200,712.00,02:21,"[1.01, 1.09]","[Fire, Flying, Psychic, Rock]","[{'num': '014', 'name': 'Kakuna'}, {'num': '01...",{},2,21,141
13,14,014,Kakuna,http://www.serebii.net/pokemongo/pokemon/014.png,"[Bug, Poison]",0.61 m,10.0 kg,Weedle Candy,50.0,Not in Eggs,0.4400,44.00,02:30,"[3.01, 3.41]","[Fire, Flying, Psychic, Rock]","[{'num': '015', 'name': 'Beedrill'}]","[{'num': '013', 'name': 'Weedle'}]",2,30,150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,144,144,Articuno,http://www.serebii.net/pokemongo/pokemon/144.png,"[Ice, Flying]",1.70 m,55.4 kg,None,NaN,Not in Eggs,0.0000,0.00,0:0,None,"[Fire, Electric, Rock, Steel]",{},{},0,0,0
144,145,145,Zapdos,http://www.serebii.net/pokemongo/pokemon/145.png,"[Electric, Flying]",1.60 m,52.6 kg,None,NaN,Not in Eggs,0.0000,0.00,0:0,None,"[Ice, Rock]",{},{},0,0,0
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"[Fire, Flying]",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0:0,None,"[Water, Electric, Rock]",{},{},0,0,0
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0:0,None,"[Bug, Ghost, Dark]",{},{},0,0,0
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0:0,None,"[Bug, Ghost, Dark]",{},{},0,0,0

These are all Pokemons whose spawn time is less than 300 seconds.

### ● Get all Pokemon who have more than two types of capabilities

In [207]:
dn.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,sp_min,sp_sec,sp_time
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",{},20,0,1200
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",7,0,420
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,None,"[Fire, Ice, Flying, Psychic]",{},"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",11,30,690
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",{},8,45,525
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",19,0,1140

In [208]:
dn.type.value_counts()

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1709, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[Water]               18
[Normal]              16
[Fire]                10
[Poison]              10
[Grass, Poison]        9
[Normal, Flying]       8
[Electric]             8
[Psychic]              8
[Fighting]             7
[Ground]               6
[Bug, Poison]          5
[Rock, Ground]         4
[Rock, Water]          4
[Bug]                  3
[Water, Psychic]       3
[Ghost, Poison]        3
[Water, Ice]           3
[Bug, Grass]           2
[Water, Poison]        2
[Bug, Flying]          2
[Grass, Psychic]       2
[Poison, Ground]       2
[Fire, Flying]         2
[Ground, Rock]         2
[Poison, Flying]       2
[Dragon]               2
[Electric, Flying]     1
[Ice, Flying]          1
[Dragon, Flying]       1
[Grass]                1
[Rock, Flying]         1
[Water, Fighting]      1
[Ice, Psychic]         1
[Water, Flying]        1
Name: type, dtype: int64

There is no column showing any information about capabilities. 
Therefore it can't be calculated.