Question 3: -
Write a program, which would download the data from the provided link, and then read the data and convert
that into properly structured data and return it in Excel format.
Note - Write comments wherever necessary explaining the code written.

In [1]:
import pandas as pd

In [2]:
link = 'https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json'

In [3]:
df = pd.read_json(link)
df

                                               pokemon
0    {'id': 1, 'num': '001', 'name': 'Bulbasaur', '...
1    {'id': 2, 'num': '002', 'name': 'Ivysaur', 'im...
2    {'id': 3, 'num': '003', 'name': 'Venusaur', 'i...
3    {'id': 4, 'num': '004', 'name': 'Charmander', ...
4    {'id': 5, 'num': '005', 'name': 'Charmeleon', ...
..                                                 ...
146  {'id': 147, 'num': '147', 'name': 'Dratini', '...
147  {'id': 148, 'num': '148', 'name': 'Dragonair',...
148  {'id': 149, 'num': '149', 'name': 'Dragonite',...
149  {'id': 150, 'num': '150', 'name': 'Mewtwo', 'i...
150  {'id': 151, 'num': '151', 'name': 'Mew', 'img'...

[151 rows x 1 columns]

In [4]:
data = df.pokemon
data

0      {'id': 1, 'num': '001', 'name': 'Bulbasaur', '...
1      {'id': 2, 'num': '002', 'name': 'Ivysaur', 'im...
2      {'id': 3, 'num': '003', 'name': 'Venusaur', 'i...
3      {'id': 4, 'num': '004', 'name': 'Charmander', ...
4      {'id': 5, 'num': '005', 'name': 'Charmeleon', ...
                             ...
146    {'id': 147, 'num': '147', 'name': 'Dratini', '...
147    {'id': 148, 'num': '148', 'name': 'Dragonair',...
148    {'id': 149, 'num': '149', 'name': 'Dragonite',...
149    {'id': 150, 'num': '150', 'name': 'Mewtwo', 'i...
150    {'id': 151, 'num': '151', 'name': 'Mew', 'img'...
Name: pokemon, Length: 151, dtype: object

In [5]:
dn = pd.json_normalize(data)
dn

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.8399999999999999]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN

### Writing a compact program :-

In [6]:
import pandas as pd
import requests

def download_data(url):
    response = requests.get(url)
    if response.status_code == 200:
        return response.content
    else:
        raise Exception(f"Failed to download data. Status code: {response.status_code}")

def process_data(data):
    # reading by pandas json reader as the data is in the json format
    df = pd.read_json(data)
    
    # extracting the data from the pokemon column to expand 
    data = df.pokemon
    
    # expanding the data and creating a new dataframe
    dn = pd.json_normalize(data)
    
    return dn

def convert_to_excel(dataframe, output_file):
    dataframe.to_excel(output_file, index=False)

# link to the data we want to download
data_link = "https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json"

try:
    # Download the data
    downloaded_data = download_data(data_link)
    
    # Process the data
    processed_data = process_data(downloaded_data)
    
    # Convert to Excel and save the file
    excel_file = "output.xlsx"
    convert_to_excel(processed_data, excel_file)
    
    print(f"Data downloaded, processed, and saved as '{excel_file}' successfully.")
except Exception as e:
    print(f"An error occurred: {str(e)}")

Data downloaded, processed, and saved as 'output.xlsx' successfully.